version: '1'

services:
  postgres:
    image: 'postgres:12.16-alpine3.18'
    container_name: network-api
    env_file:
      - .env  # must define POSTGRES_USER, POSTGRES_PASSWORD and POSTGRES_DB
    volumes:
      - database-data:/var/lib/postgresql/data/  # persist data
    ports:
      - '8778:5432'  # required to access DB from host system

volumes:
  database-data:
